//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class MusicDotStartEntities : DbContext
{
    public MusicDotStartEntities()
        : base("name=MusicDotStartEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<audio> audios { get; set; }
    public virtual DbSet<genre> genres { get; set; }
    public virtual DbSet<reaction> reactions { get; set; }
    public virtual DbSet<reaction1> reactions1 { get; set; }
    public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    public virtual DbSet<user> users { get; set; }
    public virtual DbSet<Organization> Organizations { get; set; }
}
